# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!
def shared_pods
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'Reveal-SDK', '~> 10', :configurations => ['Debug']
end
target 'FlexLayoutSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  shared_pods
  use_frameworks!

  # Pods for FlexLayoutSample

end
